name: build 

on:
  workflow_dispatch:
  #push:
    #paths-ignore:
      #- "**.md"
      #- LICENSE
      #- .github/FUNDING.yml
    #branches: [main, dev]
  #pull_request:
    #paths-ignore:
      #- "**.md"
      #- LICENSE
      #- .github/FUNDING.yml
    #branches: [main]

env:
  BUILD_TOML: configs/win_rg.build.toml
  OS: windows
  SIZE: 32
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Installing Node Dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
        continue-on-error: false

      - name: Print cbmp version
        run: npx cbmp --version

      - name: Rendering Bitmaps
        run: yarn render
        continue-on-error: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Installing PyPi Dependencies
        run: python -m pip install --upgrade pip clickgen
        continue-on-error: false

      - name: Print clickgen Version
        run: |
          clickgen --version
          ctgen --version

      - name: Build cursor size
        run: ctgen $BUILD_TOML -s $SIZE -p $OS -d "bitmaps/macOS" -o "out" -n "macOS" -c "macOS Cursors with size $SIZE"

      - name: Build
        run: yarn build
     
      - name: Upload Build Cursor macOS
        uses: actions/upload-artifact@main
        with:
          name:  macOS-Windows
          path: ./out
